### ISSUE TITLE
service worker

### ISSUE THREAD

**Issue by kalaiarasi7** [phuu/ServiceWorker-Polyfill#59]
service worker registration not working for me...
please provide all resource for me

**Comment by tgvashworth** [comment]
This is toy project, and no longer supported. You can do this [for realz](http://jakearchibald.com/2014/using-serviceworker-today/) now!

**Comment by paulirish** [comment]
i saw the readme is updated but can you update the project description with a "deprecated" thing of some sort?
:family:

**Comment by tgvashworth** [comment]
Done :rocket:
